#!/usr/bin/env ruby

template_path = "#{Dir.home}/.gitmessage"

if !File.exist?(template_path)
  exit 0
end

# content = File.read(template_path).split("\n")
File.open(template_path, "w") do |f|
  f.puts("")
end
